# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
GITHUB_COMMENT_REPORTER: false
DISABLE_LINTERS:
  # We are setting KUBERNETES_DIRECTORY to the helm chart so the
  # KUBERNETES_HELM linter can find the chart, but then this linter expects to
  # find raw Kubernetes manifests in this directory, which isn't the case.
  # If we added a PRE_ command with a `helm template` step, and further
  # restricted the included files for this linter, it *might* work.
  - KUBERNETES_KUBECONFORM
  # TBD how to use this from Megalinter with our setup.
  - KUBERNETES_KUBESCAPE
  # Pylint errors on missing dependencies, and is redundant with ruff.
  - PYTHON_PYLINT
  # Pyright errors on missing dependencies.
  - PYTHON_PYRIGHT
  # yamllint is sufficient for us.
  - YAML_PRETTIER
DISABLE_ERRORS_LINTERS:
  # This may be informative but doesn't need to break the build.
  - COPYPASTE_JSCPD
  # TBD! Need to work through these.
  - DOCKERFILE_HADOLINT
  - REPOSITORY_KICS
  - REPOSITORY_CHECKOV
  - REPOSITORY_TRIVY
  # Making optional to not block builds, even though it's still important!
  - SPELL_CSPELL
SPELL_CSPELL_ANALYZE_FILE_NAMES: false
# Ignore YAML files with templating macros; these typically fail linting and/or
# schema checking.
FILTER_REGEX_EXCLUDE: '(templates/.*\.yml|templates/.*\.yaml)'
KUBERNETES_DIRECTORY: charts/lfx-platform
KUBERNETES_HELM_ARGUMENTS: charts/lfx-platform
