# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
extends: default
ignore: |
  .git
  megalinter-reports
  styles
  venv
  .venv
  charts/lfx-v1-sync-helper/templates
rules:
  line-length:
    max: 120
    level: warning
  indentation:
    # Meltano doesn't indent sequences, but we otherwise do.
    indent-sequences: whatever
